name: Destroy AWS Infrastructure

on:
  workflow_dispatch:  # 수동 실행만 가능
    inputs:
      confirm:
        description: 'Type "DESTROY" to confirm infrastructure deletion'
        required: true
        type: string

env:
  AWS_REGION: ap-northeast-2
  APP_NAME: honbabnono

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Validate confirmation
      if: github.event.inputs.confirm != 'DESTROY'
      run: |
        echo "❌ Confirmation failed. You must type 'DESTROY' to proceed."
        exit 1
        
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
        terraform_wrapper: false
        
    - name: Initialize Terraform
      run: |
        cd terraform
        terraform init
        
    - name: Scale down ECS service
      run: |
        aws ecs update-service \
          --cluster ${{ env.APP_NAME }}-cluster \
          --service ${{ env.APP_NAME }}-service \
          --desired-count 0 \
          --region ${{ env.AWS_REGION }} || true
          
    - name: Wait for tasks to stop
      run: |
        aws ecs wait services-stable \
          --cluster ${{ env.APP_NAME }}-cluster \
          --services ${{ env.APP_NAME }}-service \
          --region ${{ env.AWS_REGION }} || true
          
    - name: Destroy infrastructure
      run: |
        cd terraform
        terraform destroy -auto-approve
        
    - name: Cleanup notification
      run: |
        echo "🧹 Infrastructure destroyed successfully!"
        echo "💰 All AWS resources have been deleted to stop charges."